
/* **** DO NOT EDIT - this file is generated by ARChitect2 ****
 *
 * Description: Header file declaring the compiler extensions for eia components 
 */

#ifndef _io_config_H_
#define _io_config_H_

/* Original version from Synopsys toolchain ....*/
#define IO_ADC0_PRESENT
#define IO_ADC0_FS (32)
#define IO_ADC0_SE (32)
#define IO_ADC0_INT_ERR (18)
#define IO_ADC0_INT_IRQ (19)
#define IO_CREG_MST0_PRESENT
#define IO_CREG_SLV0_PRESENT
#define IO_CREG_SLV1_PRESENT
#define IO_GPIO_8B0_PRESENT
#define IO_GPIO_8B0_INT_INTR_FLAG (20)
#define IO_GPIO_8B1_PRESENT
#define IO_GPIO_8B1_INT_INTR_FLAG (21)
#define IO_I2C_MST0_PRESENT
#define IO_I2C_MST0_FS (8)
#define IO_I2C_MST0_INT_ERR (22)
#define IO_I2C_MST0_INT_RX_AVAIL (23)
#define IO_I2C_MST0_INT_TX_REQ (24)
#define IO_I2C_MST0_INT_STOP_DETECTED (25)
#define IO_I2C_MST1_PRESENT
#define IO_I2C_MST1_FS (8)
#define IO_I2C_MST1_INT_ERR (26)
#define IO_I2C_MST1_INT_RX_AVAIL (27)
#define IO_I2C_MST1_INT_TX_REQ (28)
#define IO_I2C_MST1_INT_STOP_DETECTED (29)
#define IO_SPI_MST0_PRESENT
#define IO_SPI_MST0_FS (8)
#define IO_SPI_MST0_INT_ERR (30)
#define IO_SPI_MST0_INT_RX_AVAIL (31)
#define IO_SPI_MST0_INT_TX_REQ (32)
#define IO_SPI_MST1_PRESENT
#define IO_SPI_MST1_FS (8)
#define IO_SPI_MST1_INT_ERR (33)
#define IO_SPI_MST1_INT_RX_AVAIL (34)
#define IO_SPI_MST1_INT_TX_REQ (35)



// Need to decide where these should reside - probably some common header file
//@@@
// TODO Add description for these macros
#define NUM_INTERRUPTS              256

#define AUX_IRQ_CTRL_SAVE_ALL       (0x1F | (1 << 9) | (1 << 10))
#define AUX_IRQ_CTRL                0x0E

#define AUX_IRQ_SELECT              0x40B
#define AUX_IRQ_PRIO                0x206

#define AUX_REG_IVT_BASE            0x25

#define CLR_INT asm("CLRI;")
#define SET_INT asm("SETI;")

#define I2C_PRIORITY                1
#define SPI_PRIORITY                1
#define MAILBOX_INTERRUPT_PRIORITY  1
#define UART_PRIORITY               1
#define GPIO_PRIORITY               1
#define DMAC_PRIORITY               1

#define MAILBOX_SS_INT_VECTOR       (57)

// UART0
#define IO_UART0_INT                (41)
#define IO_UART1_INT                (42)

// I2C
#define SOC_I2C_0_INT               (36)
#define SOC_I2C_1_INT               (37)

// DMAC
#define DMA_CHANNEL_0_INT           (49)
#define DMA_CHANNEL_1_INT           (50)
#define DMA_CHANNEL_2_INT           (51)
#define DMA_CHANNEL_3_INT           (52)
#define DMA_CHANNEL_4_INT           (53)
#define DMA_CHANNEL_5_INT           (54)
#define DMA_CHANNEL_6_INT           (55)
#define DMA_CHANNEL_7_INT           (56)
#define DMA_ERROR_INT               (60)

#endif


