#ifndef __IPC_REQUESTS_H__
#define __IPC_REQUESTS_H__

#define IPC_MSG_TYPE_MESSAGE 0x1
#define IPC_MSG_TYPE_FREE    0x2
#define IPC_MSG_TYPE_SYNC    0x3

#define IPC_REQUEST_ALLOC_PORT         0x10
#define IPC_REQUEST_REGISTER_SERVICE   0x11
#define IPC_REQUEST_DEREGISTER_SERVICE 0x12
#define IPC_REQUEST_REG_TCMD_ENGINE    0x13

#endif
